resources:
  Dbp\Relay\AuthorizationBundle\Entity\Group:
    shortName: "AuthorizationGroup"
    normalizationContext:
      groups: ["AuthorizationGroup:output"]
    denormalizationContext:
      groups: ["AuthorizationGroup:input"]
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\AuthorizationBundle\Rest\GroupProvider
        uriTemplate: "/authorization/groups/{identifier}"
        openapiContext:
          tags: ["Authorization"]
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\AuthorizationBundle\Rest\GroupProvider
        uriTemplate: "/authorization/groups"
        openapiContext:
          tags: ["Authorization"]
      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\AuthorizationBundle\Rest\GroupProcessor
        uriTemplate: "/authorization/groups"
        openapiContext:
          tags: ["Authorization"]
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  properties:
                    name:
                      type: "string"
                  required:
                    - name
                example:
                  name: "Example Group Name"

      ApiPlatform\Metadata\Delete:
        provider: Dbp\Relay\AuthorizationBundle\Rest\GroupProvider
        processor: Dbp\Relay\AuthorizationBundle\Rest\GroupProcessor
        uriTemplate: "/authorization/groups/{identifier}"
        openapiContext:
          tags: ["Authorization"]
    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'

  Dbp\Relay\AuthorizationBundle\Entity\Resource:
    shortName: "AuthorizationResource"
    normalizationContext:
      groups: [ "AuthorizationResource:output" ]
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\AuthorizationBundle\Rest\ResourceProvider
        uriTemplate: "/authorization/resources/{identifier}"
        openapiContext:
          tags: [ "Authorization" ]
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\AuthorizationBundle\Rest\ResourceProvider
        uriTemplate: "/authorization/resources"
        openapiContext:
          tags: [ "Authorization" ]
    properties:
      identifier:
        identifier: true
      resourceClass:
        iri: 'https://schema.org/additionalProperty'
      resourceIdentifier:
        iri: 'https://schema.org/identifier'

  Dbp\Relay\AuthorizationBundle\Entity\ResourceActionGrant:
    shortName: "AuthorizationResourceActionGrant"
    normalizationContext:
      groups: [ "AuthorizationResourceActionGrant:output" ]
    denormalizationContext:
      groups: [ "AuthorizationResourceActionGrant:input" ]
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\AuthorizationBundle\Rest\ResourceActionGrantProvider
        uriTemplate: "/authorization/resource-action-grants/{identifier}"
        openapiContext:
          tags: [ "Authorization" ]
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\AuthorizationBundle\Rest\ResourceActionGrantProvider
        uriTemplate: "/authorization/resource-action-grants"
        openapiContext:
          tags: [ "Authorization" ]
      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\AuthorizationBundle\Rest\ResourceActionGrantProcessor
        uriTemplate: "/authorization/resource-action-grants"
        openapiContext:
          tags: [ "Authorization" ]
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  properties:
                    namespace:
                      type: "string"
                    resourceIdentifier:
                      type: "string"
                    action:
                      type: "string"
                    userIdentifier:
                      type: "string"
                    groupIdentifier:
                      type: "string"
                  required:
                    - namespace
                    - action
                example:
                  authorizationResourceIdentifier: "<identifier of AuthorizationResource item>"
                  action: "write"
                  userIdentifier: "811EC3ACC0ADCA70" # woody007

      ApiPlatform\Metadata\Delete:
        provider: Dbp\Relay\AuthorizationBundle\Rest\ResourceActionGrantProvider
        processor: Dbp\Relay\AuthorizationBundle\Rest\ResourceActionGrantProcessor
        uriTemplate: "/authorization/resource-action-grants/{identifier}"
        openapiContext:
          tags: [ "Authorization" ]
    properties:
      identifier:
        identifier: true
      authorizationResourceIdentifier:
        iri: 'https://schema.org/identifier'
      action:
        iri: 'https://schema.org/Action'
      userIdentifier:
        iri: 'https://schema.org/identifier'
      groupIdentifier:
        iri: 'https://schema.org/identifier'
