resources:
  Dbp\Relay\AuthorizationBundle\Entity\Group:
    types: ['https://schema.org/Group']
    shortName: "AuthorizationGroup"
    normalizationContext:
      groups: ["AuthorizationGroup:output"]
    denormalizationContext:
      groups: ["AuthorizationGroup:input"]
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\AuthorizationBundle\Rest\GroupProvider
        uriTemplate: "/authorization/groups/{identifier}"
        openapiContext:
          tags: ["Authorization"]
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\AuthorizationBundle\Rest\GroupProvider
        uriTemplate: "/authorization/groups"
        openapiContext:
          tags: ["Authorization"]
      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\AuthorizationBundle\Rest\GroupProcessor
        uriTemplate: "/authorization/groups"
        openapiContext:
          tags: ["Authorization"]
      ApiPlatform\Metadata\Delete:
        provider: Dbp\Relay\AuthorizationBundle\Rest\GroupProvider
        processor: Dbp\Relay\AuthorizationBundle\Rest\GroupProcessor
        uriTemplate: "/authorization/groups/{identifier}"
        openapiContext:
          tags: ["Authorization"]
    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'
