services:
  Dbp\Relay\AuthorizationBundle\Rest\:
    resource: '../../Rest'
    autowire: true
    autoconfigure: true

  Dbp\Relay\AuthorizationBundle\Command\:
    resource: '../../Command'
    autowire: true
    autoconfigure: true

  Dbp\Relay\AuthorizationBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true
    calls:
      - setCache: [ '@dbp.relay.authorization.cache.authorization_service' ]

  Dbp\Relay\AuthorizationBundle\Service\GroupService:
    autowire: true
    autoconfigure: true
    arguments:
      $entityManager: '@doctrine.orm.dbp_relay_authorization_bundle_entity_manager'

  Dbp\Relay\AuthorizationBundle\Service\InternalResourceActionGrantService:
    autowire: true
    autoconfigure: true
    arguments:
      $entityManager: '@doctrine.orm.dbp_relay_authorization_bundle_entity_manager'

  Dbp\Relay\AuthorizationBundle\API\ResourceActionGrantService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\AuthorizationBundle\Service\UserAttributeProvider:
    autowire: true
    autoconfigure: true

  dbp.relay.authorization.cache.authorization_service:
    parent: cache.app
    tags:
      - { name: 'cache.pool', default_lifetime: 360 }
