<?php

declare(strict_types=1);

namespace Dbp\Relay\AuthorizationBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240508065756 extends EntityManagerMigration
{
    public function getDescription(): string
    {
        return '(re-)create authorization and group tables';
    }

    public function up(Schema $schema): void
    {
        // the following is auto-generated by the 'doctrine:migrations:diff' command
        $this->addSql('CREATE TABLE authorization_group_members (identifier BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', parent_group_identifier BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', child_group_identifier BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', user_identifier VARCHAR(40) DEFAULT NULL, INDEX IDX_D819EFC5147F90EB (parent_group_identifier), UNIQUE INDEX UNIQ_D819EFC5E50822CE (child_group_identifier), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE authorization_groups (identifier BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', name VARCHAR(64) NOT NULL, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE authorization_resource_action_grants (identifier BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', authorization_resource_identifier BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', group_identifier BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', action VARCHAR(40) NOT NULL, user_identifier VARCHAR(40) DEFAULT NULL, dynamic_group_identifier VARCHAR(40) DEFAULT NULL, INDEX IDX_A1022A98213E78E1 (authorization_resource_identifier), INDEX IDX_A1022A98A0E3E2D8 (group_identifier), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE authorization_resources (identifier BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', resource_class VARCHAR(40) NOT NULL, resource_identifier VARCHAR(40) DEFAULT NULL, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE authorization_group_members ADD CONSTRAINT FK_D819EFC5147F90EB FOREIGN KEY (parent_group_identifier) REFERENCES authorization_groups (identifier)');
        $this->addSql('ALTER TABLE authorization_group_members ADD CONSTRAINT FK_D819EFC5E50822CE FOREIGN KEY (child_group_identifier) REFERENCES authorization_groups (identifier)');
        $this->addSql('ALTER TABLE authorization_resource_action_grants ADD CONSTRAINT FK_A1022A98213E78E1 FOREIGN KEY (authorization_resource_identifier) REFERENCES authorization_resources (identifier)');
        $this->addSql('ALTER TABLE authorization_resource_action_grants ADD CONSTRAINT FK_A1022A98A0E3E2D8 FOREIGN KEY (group_identifier) REFERENCES authorization_groups (identifier)');
    }

    public function down(Schema $schema): void
    {
        // the following is auto-generated by the 'doctrine:migrations:diff' command
        $this->addSql('DROP TABLE authorization_group_members');
        $this->addSql('DROP TABLE authorization_groups');
        $this->addSql('DROP TABLE authorization_resource_action_grants');
        $this->addSql('DROP TABLE authorization_resources');
    }
}
